### ISSUE TITLE
Create web page frames according to user Stories

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#3]
https://github.com/UF-CEN5035-2022SpringProject/GatorStore/blob/main/sprint1/SE-SellerPageDesign.jpg

This is just a showcase. We need more detailed frames for pages.

Doc of the frame:
https://miro.com/app/board/uXjVOT8IzTY=/

**Comment by yimingStar** [comment]
Please try to draw simple frame and we can discuss later
@vivaan-11 
1. Landing Page
2. ProductList Page

@llerenabarruetos 
1. User Info & StoreList Page
2. Product detail Page

There are a few common components we must consider
1. Header Component or Side Bar List
    - Login 
    - SignUp
    - Personal Detail and Settings

**Comment by llerenabarruetos** [comment]
**First Iteration of Pages 2 and 4:**

Page 2: Store List Page:
![image](https://user-images.githubusercontent.com/40399062/150698361-0013c510-2228-4e23-8208-b8f1e0c1410b.png)
What: This page lists all the stores that this seller (user) manages. Each store has:
- name of store
- list of items currently on sale ("active items")
- other past history:
- List of items ever sold
- List of items ever published
- total revenue ever made
- Store rating (or should it be seller rating - shown for all their stores)


Page 4: Product Page
![image](https://user-images.githubusercontent.com/40399062/150698410-ac9c7632-9a4f-4439-8f20-97d0538ac553.png)
What: A product's page contains:
- product title/name
- image
- price
- what store is selling it
- Whose store is this?
- Shipping info (time frame and additional costs)
- Description
- Reviews?
- Related products?
- Other Products from this store/seller?

(Miro Link to view Full Board: https://miro.com/app/board/uXjVOT8IzTY=/ )

**Comment by yimingStar** [comment]
@llerenabarruetos Well done!

There are a few things I would like to discuss:
1. Since it is a Seller management web page, the action will be EDIT, UPDATE, CREATE
    - Page 2: Might need a CREATE store action
    - Page 4: Product Page might need more actions and removing the purchase action (This is a great design for Buyer page)
  
2. I would discuss a feature with you on the second page. 
   Do you think we need a component to show user information? 
   I'm thinking to add a component of this at the top of the store list since it will be more clear which user store list 
   For example -[https://imgur.com/M1720Da](https://imgur.com/M1720Da)

**Comment by llerenabarruetos** [comment]
@yimingStar That is great feedback. I added some of it on Miro for us to discuss on tomorrow's meeting. Feel free to change it on Miro before or during the meeting!

### **Page 2: After Yiming's Feedback:**
![image](https://user-images.githubusercontent.com/40399062/151032160-1f76f3a7-e77c-47d9-96ff-2b7d5d58edec.png)
Added Yiming's feedback of abilities to create, edit, delete, update (done with "edit store" button as well).
Discussion Points:
- Is it a good idea to have "edit" and "delete" too close to each other? Even though "delete" will probably have a pop-up prompt to confirm deletion. Any better places to put delete?
- Is it necessary to be able to go see a store from the user's POV from this page?


### **Page 4: After Yiming's Feedback:**
![image](https://user-images.githubusercontent.com/40399062/151032328-313f283a-a285-4ec7-b068-69f46ddd65a2.png)
"Edit Details" (which replaces the Purchase button) was added. But the alternative is putting the edit (pencil) icon next to the title, price, shipping info (not here yet), description, etc - which we could also do if you would like.
Another idea is to make an overlay that becomes visible when "Edit Details" is clicked, and in it will be fields to edit all the product information.


**Regarding a component to show the seller's information,** yea, I think that'd be very useful. It could also be part of the header: instead of the user icon and "Account", it becomes the user's (in this case, a seller) profile picture and username (which could lead to a dropdown of basic account options if clicked). Good call!

**Comment by yimingStar** [comment]
@llerenabarruetos Great job!
Let's focus on the discuss the header in the meeting and I'll leave some details here
1. Login btn/ Account btn
2. User information
3. GatorStore image

**Comment by yimingStar** [comment]
[page1&page3.pdf](https://github.com/UF-CEN5035-2022SpringProject/GatorStore/files/7946561/page1.page3.pdf)

Page1
1. Disuccuss landing page, login/sign up 
2. Adding description area and introduction of our product
    [Example web page](https://getshogun.com/page-builder/ecommerce-templates)

Page3
1. This will be a page for the seller, so the add to cart and cart will be on the buyer web page
2. The username showing avatar is great

**Comment by yimingStar** [comment]
Meeting 1/26
Frontend

Header
1. SignIn Btn / User avatar -> like the one Vivanan drew at Page3
2. Putting Store names on Page3 and Page 4
3. Google Login Btn + Oauth2 process

Backend
1. Start implementation Google login Oauth2 process
2. Store user data and create API for objects @chouhy 
    - User
    - Store
    - Product

**Comment by vivaan-11** [comment]
First Iteration of Login Page and Product List Page:                                                                                                                                               
[Sprint 1.pdf](https://github.com/UF-CEN5035-2022SpringProject/GatorStore/files/7946667/Sprint.1.pdf)
Description of Login Page:

- Header
- Logo
- Login Button with Google Logo
- Footer

Description of Product List Page:

- Header with Search Bar, Home Button, Cart, User Information
- Sorting and Filtering Column
- Product Cards containing Product Name, Product Price and Add to Cart Button
- Footer

**Comment by yimingStar** [comment]
@vivaan-11 
Please adjust your frame. Remove the add card and the functions which are not for sellers.
And please add these area to the landing page
1. Product introduction
2. About our team
3. Start free trial btn

**Comment by vivaan-11** [comment]
@yimingStar 
I have made the required changes to the product list frame:
![MacBook Pro 14_ - 2](https://user-images.githubusercontent.com/97711523/152089899-469317cb-f02f-4042-8181-9d22d75c6ffd.jpg)
I have also made the landing page frame with the requirements you listed:
![MacBook Pro 14_ - 1](https://user-images.githubusercontent.com/97711523/152089945-0f1a08ca-91c9-4829-8c4c-b8f31fef8c44.jpg)

**Comment by yimingStar** [comment]
@vivaan-11 
One question about the area rotating images, what content are you planning to use in this area?

**Comment by vivaan-11** [comment]
It will contain a carousel of images where we can highlight the stores present in our store and displaying any offers or promotions they might have and want to display on the landing page.
