### ISSUE TITLE
Cypress unable to automatically use Google Login

### ISSUE THREAD

**Issue by yimingStar** [UF-CEN5035-2022SpringProject/GatorStore#67]

**Comment by llerenabarruetos** [comment]
Up to this point, Cypress has been unable to properly automate logging in a user through Google.   

2 approaches have been tried so far:
1. Cypress's Library of "cypress-social-logins" [(Documentation)](https://github.com/lirantal/cypress-social-logins)    
This library's functionality is cut short by either a Google 403 error, a Google error pertaining to cookies of a browser, and a Google error saying that the current browser is not secure - all of which happen before showing the field for the user's password in Google's authentication page. Cypress only interacts with elements from the origin of a test, in this case, that is localhost:3000. Going to the Google login page brings the test to a new origin, which is denied by Google's security measures.
While the library might have worked before, it currently is subject to tighter security measures from Google regarding the browser where the website is ran and testing program controlling it (from 2020).     

Cypress offers several browsers to run the tests in (Such as Chrome, Edge 98, and their built-in Electron browser). The available browsers in my system (Chrome, Edge, Firefox, and their Electron browser) were all tested and all had problems with either Google's 403 error, cookies (from Google) not being allowed on the browser, or Google's "this browser is not secure" error. Apparently, it has been a few years since Google has taken harsher measures to prevent bots or automated browsers from accessing their resources such as with Authentication.

A similar issue can be found [here.](https://github.com/lirantal/cypress-social-logins/issues/43).   

2. Programmatically Interact with Google's Authentication API [(Document/Tutorial)](https://docs.cypress.io/guides/testing-strategies/google-authentication#Google-Developer-Console-Setup)      
This was one of the practices [recommended ](https://docs.cypress.io/guides/references/best-practices#Visiting-external-sites) by Cypress.
It involves sending a POST request to Google's login url. However, we discovered that **manually inputting a password and an email combination is a required step before Google lets you use it to log in** (and gives the user code we want to pass to our API to retrieve a user's JWToken, email, name, etc.).

**Comment by llerenabarruetos** [comment]
The next approaches that will be attempted to test Google Login will be:

1. [Selenium](https://www.selenium.dev)
2. [Puppeteer v13.4.1](https://pptr.dev)

**Comment by yimingStar** [comment]
Selenium seems to have the same problem
Since Google change there core driver for some policy, using the driver for automation purpose needs to find new work around to solve them.
